version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: interview_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: POSTGRESQL_PASSWORD
      TZ: Asia/Seoul
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command:
      - "postgres"
      - "-c"
      - "timezone=Asia/Seoul"

  redis:
    image: redis:latest
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    network_mode: "host"
    command: --httpPort=8081
#    ports:
#      - "8081:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /home/ubuntu/budbut:/home/ubuntu/budbut
    restart: always
    environment:
      - TZ=Asia/Seoul
#    environment:
#      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false -Dserver.port=8081

volumes:
  postgres_data:
  jenkins_home:
