spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/interview_db
    username: admin
    password: POSTGRESQL_PASSWORD
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  data:
    redis:
      host: localhost
      port: 6379

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
